# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04c19d7886385ee6ab98242f7ff2688bb2674853edc7a490c408eb964223c1345e3a8e15a31fc05076fef88aea1efb12c77cea7e42de876e8ee999508d7d5ee4

test:
  secret_key_base: 761b245029c667ae6219034603da585ca1f48e412e9ba1957a90eac1a35c47a9bc010856e4e9e954967146f97a970f9244064514e233e36c4af5c454d96ed2ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
